namespace Compiler
{
    public enum TokenType
    {
        End_of_input, Op_multiply, Op_divide, Op_mod, Op_add, Op_subtract,
        Op_negate, Op_not, Op_less, Op_lessequal, Op_greater, Op_greaterequal,
        Op_equal, Op_notequal, Op_assign, Op_and, Op_or, Keyword_if,
        Keyword_else, Keyword_while, Keyword_print, Keyword_putc, LeftParen, RightParen,
        LeftBrace, RightBrace, Semicolon, Comma, Identifier, Integer, Float, String, None,
        Op_bit_or,
        Op_bit_not,
        Include,

        Keyword_auto,
        Keyword_double,
        Keyword_int,
        Keyword_struct,
        Keyword_break,
        Keyword_long,
        Keyword_switch,
        Keyword_case,
        Keyword_enum,
        Keyword_register,
        Keyword_typedef,
        Keyword_char,
        Keyword_extern,
        Keyword_return,
        Keyword_continue,
        Keyword_for,
        Keyword_signed,
        Keyword_void,
        Keyword_do,
        Keyword_static,
        Keyword_goto,
        Keyword_sizeof,
        Keyword_volatile,
        Keyword_const,
        Keyword_float,
        Keyword_short,
        Keyword_unsigned,

        Op_bit_xor,
        Op_bit_left_shift,
        Op_bit_right_shift,
        Op_add_assign,
        Op_sub_assign,
        Op_multiply_assign,
        Op_bit_and_assign,
        Op_bit_xor_assign,
        Op_bit_left_shift_assign,
        Op_bit_right_shift_assign,
        Op_struct_reference,

        LeftSquareBracket,
        RightSquareBracket,
        Op_bit_or_assign,
        Error,
        Keyword_union,
        Keyword_default,

        Op_pre_inc,
        Op_pre_dec,
        Op_suf_inc,
        Op_suf_dec,
        Op_pointer,
        Op_reference,
        Op_bit_and,
        Char
    }
}